### ISSUE TITLE
client disconect due to nbt size

### ISSUE THREAD

**Issue by teak1** [GirafiStudios/Impractical-Storage#60]
I've created a storage area of size 16x63x16 and am forced to leave the server due to the nbt being to large

forge: forge-14.23.4.2707
pack: http://github.com/andrewminer/brunel

Server Info:
(will be added in edit when posible)

**Comment by dmillerw** [comment]
Stack trace? Crash log?

**Comment by teak1** [comment]
```
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097157bytes where max allowed: 2097152
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:442)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097157bytes where max allowed: 2097152
	at net.minecraft.nbt.NBTSizeTracker.func_152450_a(NBTSizeTracker.java:25)
	at net.minecraft.nbt.NBTTagInt.func_152446_a(SourceFile:30)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58)
	at net.minecraft.nbt.NBTTagList.func_152446_a(NBTTagList.java:63)
	at net.minecraft.nbt.NBTTagCompound.func_152449_a(NBTTagCompound.java:496)
	at net.minecraft.nbt.NBTTagCompound.func_152446_a(NBTTagCompound.java:58)
	at net.minecraft.nbt.CompressedStreamTools.func_152455_a(CompressedStreamTools.java:133)
	at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:88)
	at net.minecraft.network.PacketBuffer.func_150793_b(PacketBuffer.java:315)
	at net.minecraft.network.play.server.SPacketChunkData.func_148837_a(SourceFile:75)
	at net.minecraft.network.NettyPacketDecoder.decode(SourceFile:40)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
	... 35 more
```

**Comment by GirafiStudios** [comment]
Turned out this is actually a vanilla bug. Please install the mod "Packet Fixer", which will solve this issue :)

https://www.curseforge.com/minecraft/mc-mods/packet-fixer

**Comment by GirafiStudios** [comment]
For future reference, it happens when reading a large NBTTagList. For Impratical Storage specifically nbt_worldToSlotMap or nbt_worldOcclusionMap
